### ISSUE TITLE
composer update时候报错

### ISSUE THREAD

**Issue by xinhaonaner** [DukeAnn/Laradmin#6]
`**`
git clone 后，
更新composer.json报错，麻烦看下是什么原因呢，这个ide-helper包，好像有问题
**
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "ide-helper" namespace.

Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1

**Comment by xinhaonaner** [comment]
报这个错误：
[Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "ide-helper" namespace.

Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1

**Comment by DukeAnn** [comment]
执行这个命令更新 `php artisan ide-helper:generate` ide-helper
